// 게임 흐름: 새 게임 초기화 (상태 머신/승패 기록은 Step 6에서 이쪽으로)
import { ATTACK_DURATION, MAX_MANA, expForLevel, FIRST_WAVE_DELAY } from './data/balance.js';
import { World, Body, world } from './core/physics.js';
import { game, ui, input } from './state.js';
import { giveStarterGear, giveTestStash } from './systems/gear.js';
import { SKILLS } from './systems/skills.js';
import { PEN } from './world/arena.js';

export function resetGame() {
  game.paused = false;
  game.runRecorded = false;
  const pb = document.getElementById('btn-pause');
  if (pb) pb.textContent = 'Ⅱ';

  game.cows.forEach((c) => { if (c.body) World.remove(world, c.body); });
  game.cows = [];
  game.wave = 0;
  // 시작 직후 적이 튀어나오지 않도록 준비 시간을 둠 - 이후 웨이브 사이엔 기존 WAVE_GAP 사용
  game.waveTransition = FIRST_WAVE_DELAY;
  game.waveBannerTimer = 0;
  game.demoTipTimer = 5.0;

  Body.setPosition(game.hero.body, { x: PEN.x + PEN.size / 2, y: PEN.y + PEN.size / 2 });
  Body.setVelocity(game.hero.body, { x: 0, y: 0 });
  game.hero.hp = game.hero.maxHp;
  game.hero.mana = game.hero.maxMana;
  game.hero.stamina = game.hero.maxStamina;
  game.hero.running = false;
  game.hero.invuln = 0;
  game.hero.attackTimer = 0;
  game.hero.attackCooldown = 0;
  game.hero.currentAttackDuration = ATTACK_DURATION;
  game.hero.combo = 0;
  game.hero.comboTimer = 0;
  game.hero.knockback = 0;
  game.hero.flash = 0;
  game.hero.alive = true;
  game.hero.warcryCooldown = 0;
  game.hero.whirlwindTimer = 0;
  game.hero.whirlwindCooldown = 0;
  game.hero.whirlAngle = 0;
  game.hero.leapTimer = 0;
  game.hero.leapCooldown = 0;
  game.hero.rushTimer = 0;
  game.hero.rushCooldown = 0;
  game.hero.rushHitSet = null;
  game.hero.smashTimer = 0;
  game.hero.smashCooldown = 0;
  game.hero.smashHitDone = false;
  game.hero.moveOffsetX = 0;
  game.hero.moveOffsetY = 0;
  game.hero.moveOffsetVX = 0;
  game.hero.moveOffsetVY = 0;
  game.hero.moveLean = 0;
  game.hero.moveLeanV = 0;
  game.hero.moveFxCooldown = 0;
  game.hero.moveReaction = 0;
  game.hero.moveSpeedN = 0;
  game.hero.moveInputActive = false;
  game.hero.moveStep = 0;
  game.hero.slowTimer = 0;
  game.hero.bonusMaxHp = 0;
  game.hero.vitalityTimer = 0;
  game.hero.speedMult = 1;
  game.hero.speedBuffTimer = 0;
  game.hero.attackBonus = 0;
  game.hero.attackBuffTimer = 0;
  game.hero.defenseChance = 0;
  game.hero.defenseBuffTimer = 0;
  game.hero.equipment = { armor: null, weaponMain: null, weaponOff: null, greaves: null, boots: null, accessory1: null, accessory2: null };
  game.hero.gearAtkSpeed = 0;
  game.hero.gearAtkPower = 0;
  game.hero.gearDefense = 0;
  game.hero.gearEvasion = 0;
  game.hero.gearSpeedMult = 1;
  game.hero.gearMaxHp = 0;
  game.hero.gearMaxMana = 0;
  game.hero.materials = 0;
  game.hero.inventory = [];
  game.hero.potions = { heal: 2, mana: 2 };
  game.hero.potionCd = { heal: 0, mana: 0 };
  giveStarterGear(); // gear 보너스 초기화 이후에 호출해야 장착 효과가 덮어써지지 않음
  giveTestStash(); // 장비 교체 테스트용 - 무기 종류별 1개 + 방패 + 양손무기를 가방에 바로 지급
  game.hero.hp = game.hero.maxHp + game.hero.gearMaxHp;
  game.hero.mana = game.hero.maxMana + game.hero.gearMaxMana;
  ui.identifyingItem = null;
  ui.identifyTimer = 0;
  ui.selectedInvIndex = null;
  ui.hoverInvIndex = null;
  ui.invPanelTab = 'equip';
  ui.invToast = null;
  ui.invReveal = null;
  game.hero.level = 1;
  game.hero.exp = 0;
  game.hero.expToNext = expForLevel(1);
  game.hero.statPoints = 0;
  game.hero.levelStats = { atkPower: 0, defense: 0, evasion: 0, atkSpeed: 0, moveSpeed: 0, health: 0, mana: 0 };
  game.hero.maxMana = MAX_MANA;

  game.particles = [];
  game.shockwaves = [];
  game.hazards = [];
  game.lightningBolts = [];
  game.items = [];
  game.floatTexts = [];
  game.shake = 0;
  game.hitstop = 0;
  game.impactFlash = 0;
  game.kills = 0;
  game.hero.slot1 = 'attack';
  game.hero.slot2 = 'warcry';
  input.holdSlot1 = false;
  input.holdSlot2 = false;
  const s1label = document.getElementById('slot1-label');
  const s2label = document.getElementById('slot2-label');
  const s1el = document.getElementById('slot1');
  const s2el = document.getElementById('slot2');
  if (s1label) s1label.textContent = SKILLS[game.hero.slot1].label;
  if (s2label) s2label.textContent = SKILLS[game.hero.slot2].label;
  if (s1el) s1el.style.background = SKILLS[game.hero.slot1].color;
  if (s2el) s2el.style.background = SKILLS[game.hero.slot2].color;
  game.gameState = 'playing';
}
